# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BaekYangLi' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BaekYangLi

  pod 'NVActivityIndicatorView'
  pod 'Alamofire'
  pod 'ObjectMapper'
  pod 'AlamofireObjectMapper'
  pod 'SnapKit'


  target 'BaekYangLiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BaekYangLiUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
